spring.application.name=BusTrackingSystem

# =========================================================
# SERVER
# =========================================================

server.port=${SERVER_PORT:9090}

# =========================================================
# DATABASE - AWS RDS
# =========================================================

spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT:3306}/${DB_NAME}?serverTimezone=UTC
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# =========================================================
# HIBERNATE / JPA
# =========================================================

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false


# =========================================================
# MAIL
# =========================================================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

cors.allowed-origins=${CORS_ALLOWED_ORIGINS:*}

# =========================================================
# LOGGING
# =========================================================

logging.level.root=INFO
logging.level.com.sankalpapp=INFO